advanced_features:
  entropy:
    bins: 20
  regime_switching:
    window: 50
  rolling_correlation:
    window: 50
  zscore:
    columns:
    - rsi
    - macd
    window: 100
backtesting:
  analysis:
    export:
      format: html
      path: reports/backtest
    metrics:
    - sharpe
    - sortino
    - calmar
    - max_drawdown
    - win_rate
    - profit_factor
    - expectancy
    plots:
    - equity_curve
    - drawdown
    - returns_distribution
    - monthly_returns
    - regime_analysis
  execution:
    impact_factor: 0.0001
    latency: 0.1
    market_impact: true
    partial_fills: true
  general:
    commission: 0.0001
    end_date: '2023-06-01'
    initial_capital: 100000
    slippage: 0.0001
    start_date: '2024-06-01'
  risk:
    max_drawdown: 0.05
    max_positions: 3
    position_sizing: fixed
broker:
  account_type: demo
  login: 92887059
  name: MetaTrader5
  password: ''
  server: MetaQuotes-Demo
  symbols:
  - exchange: FXCM
    lot_step: 0.01
    margin_required: 100.0
    max_lot: 100.0
    min_lot: 0.01
    name: EURUSD
    point: 0.0001
    type: forex
  - exchange: EUREX
    lot_step: 0.01
    margin_required: 1000.0
    max_lot: 100.0
    min_lot: 0.01
    name: DAX40
    point: 0.01
    type: futures
  - exchange: NASDAQ
    lot_step: 0.01
    margin_required: 500.0
    max_lot: 100.0
    min_lot: 0.01
    name: US500
    point: 0.01
    type: cfd
  - exchange: NASDAQ
    lot_step: 0.01
    margin_required: 500.0
    max_lot: 100.0
    min_lot: 0.01
    name: USTEC
    point: 0.01
    type: cfd
  timeframes:
  - minutes: 5
    name: M5
    primary: true
  - minutes: 15
    name: M15
    primary: false
  - minutes: 60
    name: H1
    primary: false
  timeout: 30000
clustering:
  algorithm: hdbscan
  evaluation:
    silhouette_threshold: 0.3
    stability_threshold: 0.7
  features:
    behavioral: true
    contextual: true
    technical: true
  max_iter: 1000
  metrics:
  - silhouette
  - calinski_harabasz
  - davies_bouldin
  n_clusters: 5
  n_init: 10
  params:
    cluster_selection_epsilon: 0.5
    metric: euclidean
    min_cluster_size: 50
    min_samples: 5
  random_state: 42
  reduction:
    method: umap
    min_dist: 0.1
    n_components: 10
    n_neighbors: 15
config: null
execution:
  monitoring:
    check_interval: 1
    error_cooldown: 300
    max_errors: 5
    timeout: 30
  order:
    max_slippage: 0.0002
    retry_attempts: 3
    retry_delay: 1
    type: market
  position:
    min_close_size: 0.1
    partial_close: true
    trailing_step: 0.0001
    trailing_stop: true
  risk:
    max_daily_loss: 0.02
    max_daily_trades: 10
    max_position_size: 0.1
features:
  behavioral:
    patterns:
    - name: candlestick_patterns
      patterns:
      - engulfing
      - hammer
      - doji
      - shooting_star
    - name: chart_patterns
      patterns:
      - double_top
      - double_bottom
      - head_shoulders
    volatility:
    - name: volatility_bursts
      threshold: 2.0
      window: 20
    - name: range_breakout
      period: 20
      threshold: 1.5
    volume:
    - name: volume_profile
      periods:
      - 1
      - 5
      - 15
      - 60
    - name: volume_imbalance
      period: 20
    - name: tick_imbalance
      period: 1000
  contextual:
    correlation:
    - assets:
      - DAX40
      - US500
      - USTEC
      - EURUSD
      - GOLD
      name: cross_asset
      period: 20
    - name: sector_rotation
      period: 60
      sectors:
      - tech
      - finance
      - energy
      - healthcare
    market:
    - features:
      - volatility
      - trend
      - volume
      n_regimes: 5
      name: market_regime
    - name: daily_direction
      threshold: 0.001
      timeframe: H1
    time:
    - name: session_time
      sessions:
      - eu
      - us
      - overlap
    - name: time_of_day
      periods:
      - morning
      - lunch
      - afternoon
      - evening
  technical:
    momentum:
    - name: rsi
      overbought: 70
      oversold: 30
      period: 14
    - fast_period: 12
      name: macd
      signal_period: 9
      slow_period: 26
    trend:
    - name: adx
      period: 14
      threshold: 25
    - name: vwap
      period: 20
    volatility:
    - name: bollinger
      period: 20
      std_dev: 2.0
    - name: atr
      period: 14
labeling:
  dynamic:
    max_periods: 50
    min_periods: 5
    volatility_factor: 2.0
  fixed_horizon:
    periods: 20
    threshold: 0.002
  horizon: 20
  method: triple_barrier
  min_return: 0.0
  threshold: 0.002
  triple_barrier:
    stop_loss: 0.002
    t1: 20
    take_profit: 0.002
  volatility_window: 20
ml:
  calibration:
    cv_folds: 5
    method: isotonic
  features:
    scaling:
      method: robust
      window: 1000
    selection:
      method: importance
      threshold: 0.01
  model:
    params:
      colsample_bytree: 0.8
      gamma: 0
      learning_rate: 0.01
      max_depth: 6
      min_child_weight: 1
      n_estimators: 1000
      reg_alpha: 0
      reg_lambda: 1
      subsample: 0.8
    type: xgboost
  training:
    cv_folds: 5
    cv_type: purged
    early_stopping_rounds: 50
    embargo_size: 10
    random_state: 42
    train_test_split: 0.8
    validation_split: 0.1
monitoring:
  alerts:
    email:
      enabled: true
      recipients:
      - recipient@email.com
      sender: your-email@gmail.com
      smtp_port: 587
      smtp_server: smtp.gmail.com
    telegram:
      bot_token: ''
      chat_id: ''
      enabled: false
  drift_detection:
    check_interval: 3600
    methods:
    - name: ks_test
      threshold: 0.05
      window: 1000
    - name: hellinger
      threshold: 0.1
      window: 1000
    - name: jensen_shannon
      threshold: 0.1
      window: 1000
  features:
    alert_threshold: 0.7
    check_interval: 3600
    drift_thresholds:
      correlation: 1.0
      default: 0.5
      mahalanobis: 1.0
      mean_shift: 0.3
      missing_rate: 0.1
      std_shift: 0.3
    window_size: 1000
  logging:
    backup_count: 5
    file: logs/trading.log
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    level: INFO
    max_size: 10485760
  performance:
    metrics:
      accuracy:
        degradation_threshold: 0.1
        threshold: 0.8
      f1:
        degradation_threshold: 0.1
        threshold: 0.7
      precision:
        degradation_threshold: 0.1
        threshold: 0.7
      recall:
        degradation_threshold: 0.1
        threshold: 0.7
    update_frequency: 100
    window_size: 1000
  system:
    cpu:
      check_interval: 60
      threshold: 0.8
    disk:
      check_interval: 300
      threshold: 0.9
    memory:
      check_interval: 60
      threshold: 0.8
paths:
  cache: cache
  data: data
  logs: logs
  models: models
  reports: reports
ppo:
  batch_size: 64
  clip_range: 0.2
  clip_range_vf: None
  ent_coef: 0.0
  gae_lambda: 0.95
  gamma: 0.99
  learning_rate: 3e-4
  max_grad_norm: 0.5
  n_epochs: 10
  n_steps: 2048
  normalize_advantage: true
  sde_sample_freq: -1
  seed: 42
  target_kl: None
  use_sde: false
  vf_coef: 0.5
rl:
  agent:
    params:
      batch_size: 64
      clip_range: 0.2
      ent_coef: 0.01
      gae_lambda: 0.95
      gamma: 0.99
      learning_rate: 0.0003
      max_grad_norm: 0.5
      n_epochs: 10
      n_steps: 2048
      vf_coef: 0.5
    type: ppo
  environment:
    action:
      bounds:
      - -1.0
      - 1.0
      type: continuous
    observation:
      market_data: true
      pnl: true
      position: true
      regime: true
    reward:
      drawdown_weight: 0.5
      pnl_weight: 1.0
      turnover_weight: 0.1
  training:
    eval_freq: 10000
    n_eval_episodes: 10
    save_freq: 50000
    tensorboard_log: logs/rl
    total_timesteps: 1000000
rl_environment:
  initial_balance: 100000.0
  lookback_window: 50
  max_position_size: 0.1
  min_bars_required: 50
  reward_scaling: 1.0
  transaction_cost: 0.0001
testing:
  end_date: '2025-06-09'
  max_steps: 1000
  start_date: '2025-03-02'
  symbol: EURUSD
  timeframes:
  - M5
  - M15
  - H1
trading:
  filters:
    max_spread: 0.0002
    min_volatility: 0.0001
    min_volume: 1000
    news_filter: true
    session_filter: false
  min_confidence: 0.5
  risk_management:
    max_daily_loss: 0.02
    max_drawdown: 0.05
    max_leverage: 1.0
    max_monthly_loss: 0.1
    max_positions: 3
    max_weekly_loss: 0.05
    position_size: 0.02
  sessions:
    asia:
      end: 09:00
      start: 00:00
    eu:
      end: '17:00'
      start: 08:00
    overlap:
      end: '16:30'
      start: '14:30'
      timezone: Europe/Berlin
    us:
      end: '23:00'
      start: '14:00'
  stops:
    break_even: true
    break_even_atr: 1.5
    stop_loss_atr: 2.0
    take_profit_atr: 3.0
    trailing_step: 0.0001
    trailing_stop: true
training:
  end_date: '2025-03-01'
  eval_freq: 10000
  save_freq: 50000
  start_date: '2024-03-01'
  symbol: EURUSD
  timeframes:
  - M5
  - M15
  - H1
  total_timesteps: 100000
